### ISSUE TITLE
Implementar el schema de firestore en Dart

### ISSUE THREAD

**Issue by baesparza** [UTPL-Rank/UTPL-Rank-Movil#1]
- [x] Crear una rama de funcionalidad desde el `master` llamada `schema-implementation`
- [x] Crear directorio de `models` en el proyecto movil
- [x] Crear archivo `academic-area.dart` y clase `AcademicArea`
- [x] Crear clase `AcademicDegree` en su archivo
- [x] Crear clase `KnowledgeArea` en su archivo
- [x] Crear clase `QuestionsBlock` en su archivo
- [x] Crear clase `Question` en su archivo
- [x] Crear clase `Attempt` en su archivo
- [x] Crear clase `User` en su archivo
- [x] Crear clase `Claims` en su archivo
- [x] Crear clase `Inscription` en su archivo
- [x] Crear clase `GamePlayed` en su archivo

Implementa todas estas clases en sus archivos, todos los tipos de dato son requeridos,   unos atributos pueden ser Nulos, esos los revisaremos el viernes como implementarlos en código, Algunos tipos de datos son `<Object>`, para estos vamos a crear una clase antes que se llamara del mismo nombre que el atributo con mayúscula, ejemplo.

- Source: 

```yml
# stats of this question
questionStats: <Object>
    # number of times this question has been answered
    timesAnswered: 38

    # number of times this question was answered correctly on first try
    correctFirstTime: 5
```
- En el codigo implementarimos una clase `QuestionStats` con su constructor y todo. y en la clase padre, creariamos una instancia de `QuestionStats`
